---
    - name: Add account for podolske 
      ansible.builtin.user:
        name: podolske
        uid: 18480
        password: "$6$OkvxJs7unetFQCEq$1MUwUqfmoFog935CBuiTTJvzjlmGMDozSpcpqT/kFpTCGpDz0p/96IuxKqZNIDHxRCVvvquj8qR58SB7aeRF5/"
        group: wheel
        comment: "Dave Podolske"
        home: /home/podolske
        state: present
#      when: ansible_facts['distribution'] == "Rocky"
    - name: Copy /home/podolske/.ssh/authorized_keys
      template:
        src: authorized_keys
        dest: /home/podolske/.ssh/
        mode: 0600
    - name: Fix /home/podolske/.ssh/ ownership and permission
      file:
        path: /home/podolske/.ssh
        owner: podolske
        mode: 0700
    - name: Fix /home/podolske/.ssh/authorized_keys ownership 
      file:
        path: /home/podolske/.ssh/authorized_keys
        owner: podolske
    - name: Add custom prompt to .bashrc
      lineinfile:
        path: /home/podolske/.bashrc
        line: "export PS1='$HOSTNAME:${PWD}> '"
    - name: Add key binding to .bashrc
      lineinfile:
        path: /home/podolske/.bashrc
        line: 'set -o vi'
    - name: Turn off title update in .bashrc
      lineinfile:
        path: /home/podolske/.bashrc
        line: 'unset PROMPT_COMMAND'
    - name: create /home/podolske/root.bashrc
      file: 
        path: /home/podolske/root.bashrc
        state: touch
        mode: 0755
    - name: update prompt in root.bashrc
      lineinfile:
        path:  /home/podolske/root.bashrc
        line: "export PS1='$HOSTNAME:${PWD}# '"
    - name: complete root.bashrc
      shell: "tail -2 ~podolske/.bashrc >> ~podolske/root.bashrc"
