---
- name: Audit login events
  hosts: dlms
  gather_facts: true
  tasks:
    - name: Make sure /etc/rsyslog.conf loads omfile module
      ansible.builtin.lineinfile:
        path: /etc/rsyslog.conf
        line: 'module(load="builtin:omfile" Template="RSYSLOG_TraditionalFileFormat")'
        insertafter: '# Use default timestamp format'
        state: present
    - name: Make sure /etc/rsyslog.conf sends to splunk master
      ansible.builtin.lineinfile:
        path: /etc/rsyslog.conf
        line: '*.info @10.62.109.187'
        state: present
