---
- name: Rebuild salt table in CMDB database
  hosts: cmdb
# note to self. create zero length csv file in advance
  tasks:
    - name: Convert RHEL output to csv
      ansible.builtin.shell:
        chdir: cmdb/
        cmd: "awk -F: -f salt2.awk < rhel-10-10.txt > rhel-10-10.csv"

    - name: Convert Ubuntu output to csv
      ansible.builtin.shell:
        chdir: cmdb/
        cmd: "awk -F: -f salt2.awk  < ubuntu-10-10.txt > ubuntu-10-10.csv"

    - name: Convert blurdev output to csv
      ansible.builtin.shell:
        chdir: cmdb/
        cmd: "awk -F: -f salt2.awk  < carrier-blurdev.txt > carrier-blurdev.csv"

    - name: Convert coresite output to csv
      ansible.builtin.shell:
        chdir: cmdb/
        cmd: "awk -F: -f salt2.awk  < carrier-coresite.txt > carrier-coresite.csv"

    - name: Convert reston output to csv
      ansible.builtin.shell:
        chdir: cmdb/
        cmd: "awk -F: -f salt2.awk  < carrier-reston.txt > carrier-reston.csv"

    - name: Copy SQL to rebuild the salt table
      copy: src=source/rebuild-salt.sql dest=/home/podolske/cmdb/rebuild-salt.sql

    - name: Recreate table called salt
      mysql_db:
        name: cmdb
        login_host: 172.17.0.2
        login_user: cmdb
        state: import
        target: /home/podolske/cmdb/rebuild-salt.sql
# nono of this is working
#      register: semprini
#    - name: show output
#      when: semprini|succeeded
#      debug: msg= "{{ semprini.stdout_lines }}"
#
