---
- name: Rebuild salt table in CMDB database
  hosts: cmdb
# note to self. create zero length csv file in advance
  tasks:
    - name: Convert RHEL output to csv
      ansible.builtin.shell:
        chdir: cmdb/
        cmd: "awk -F: -f salt2.awk < rhel-10-10.txt > rhel-10-10.csv"

    - name: Convert Ubuntu output to csv
      ansible.builtin.shell:
        chdir: cmdb/
        cmd: "awk -F: -f salt2.awk  < ubuntu-10-10.txt > ubuntu-10-10.csv"

    - name: Copy SQL to rebuild the salt table
      copy: src=source/rebuild-salt.sql dest=/home/podolske/cmdb/rebuild-salt.sql

    - name: Recreate table called salt
      mysql_db:
        name: cmdb
#        login_host: 172.17.0.2
        login_user: cmdb
        state: import
        target: /home/podolske/cmdb/rebuild-salt.sql
#      register: mysql
#    - debug: var=mysql.stdout_lines
#
#    - name: Copy Connection PHP File
#      copy: src=/source/connection.php dest=/var/www/html/
#
#    - name: Copy Index PHP file
#      copy: src=/source/index.php dest=/var/www/html/
#
