---
- hosts: asn
  become: yes
  tasks:
#    - name: create account for renaldo (Ubuntu)
#      shell: /usr/sbin/adduser  --uid 18480 --gid 100 --gecos renaldo --disabled-password renaldo
#      when: ansible_facts['distribution'] == "Ubuntu"
#    - name: create account for renaldo (Rocky)
#      shell: /usr/sbin/useradd -m -u 18481 -g 10 renaldo
#      when: ansible_facts['distribution'] == "Rocky"
#    - name: create account for renaldo (CentOS)
#      shell: /usr/sbin/useradd -m -u 18481 -g 10 renaldo
#      when: ansible_facts['distribution'] == "CentOS"


    - name: add account for crd037c (Linux)
      ansible.builtin.user:
        name: crd037c
        uid: 35614
        group: crd037c
        comment: "Anoop Ajwani"
        state: present
