---
- name: find the distribution
  hosts: all
  gather_facts: true
  tasks:
    - name: Distribution
      debug: msg="{{ ansible_distribution }}"
    - name: Distribution version
      debug: msg="{{ ansible_distribution_version }}"
    - name: Distribution major version
      debug: msg="{{ ansible_distribution_major_version }}"
    - name: OS family
      debug: var=ansible_os_family
