# Note to self.  merge this with sshd.yml
---
- name: Manage sshd for DLMS servers
  hosts: dlms
  gather_facts: true
  become: true
  tasks:
    - name: Edit sshd PermitRootLogin
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        insertafter: '#PermitRootLogin yes'
        line: 'PermitRootLogin without-password '
      notify: Restart_sshd
    - name: Edit sshd Protocol
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        insertafter: '^#Port'
        line: 'Protocol 2 '
      notify: Restart_sshd
  handlers:
    - name: Restart_sshd
      ansible.builtin.service:
        name: sshd
        state: restarted
