---
- hosts: motbuntu
  become: yes
  tasks:
    - name: Add group for dba
      ansible.builtin.group:
        name: dba
        gid: 20047
    - name: remove account for dohchoi (Doh Choi)
      ansible.builtin.user:
        name: dohchoi
        uid: 35374
        group: 20047
        comment: "Doh Choi"
        state: present
