---
- hosts: motbuntu
  gather_facts: true
    
  vars:
    nagios_server: 100.64.5.212,100.65.184.1

  tasks:
    - name: Install epel-release repository
      yum: name=epel-release state=present
   
    - name: Install nrpe
      yum: name=nrpe state=present

    - name: Install nagios-plugins-all
      yum: name=nagios-plugins-all state=present

    - name: Install iostat
      yum: name=sysstat state=present

    - name: Copy master /etc/sudoers.d/nrpe file
      copy: src=nrpe.cfg dest=/etc/nagios/ mode=644

    - name: Configure nagios server IP in nrpe configuration file
      lineinfile: 
        dest: /etc/nagios/nrpe.cfg
        regexp: allowed_hosts=
        line: allowed_hosts=127.0.0.1,{{nagios_server}},100.65.176.70 

    - name: Configure allow arguments in nrpe configuration file
      lineinfile: 
        dest: /etc/nagios/nrpe.cfg
        regexp: dont_blame_nrpe=0
        line: dont_blame_nrpe=1
      notify: restart_nrpe
    
    - name: add /etc/sudoers.d/nrpe file
      copy: src=nrpe-Rocky.sudoer dest=/etc/sudoers.d/nrpe mode=440


  handlers:
    - name: restart_nrpe
      service:
        name: nrpe
        enabled: true
        state: restarted
