---
- name: test new knowledge of ansible
  hosts: coresite
  gather_facts: true
  vars: 
    fruit: "apple"
  tasks:
#    - name: copy to existing file
#      ansible.builtin.copy:
#        content: "{{ fruit }}"
#        dest: "/home/podolske/afile"
    - name: template to existing file
      template:
        src: template.j2
        dest: "/home/podolske/afile"
#  - name: output
#    debug:
#      var: inventory_hostname
