---
- hosts: skywalker
  gather_facts: true
  tasks:
    - name: Add group for galmeida 
      ansible.builtin.group:
        name: galmeida
        gid: 20258
    - name: Add account for galmeida 
      ansible.builtin.user:
        name: galmeida
        uid: 35539
        group: galmeida
        comment: "Guilherme de Almeida"
        home: /home/galmeida
        state: present
    - name: Add group for skywalker
      ansible.builtin.group:
        name: skywalker
        gid: 20260
    - name: Add group for git 
      ansible.builtin.group:
        name: git
        gid: 20178
    - name: Add account for git 
      ansible.builtin.user:
        name: git
        uid: 35042
        group: git
        comment: "service account git"
        home: /home/git
        state: present
