---
- name: Manage SSHD
  hosts: dlms
  gather_facts: false
  become: true
  tasks:
    - name: Ensure SSHD Started and Enabled
      ansible.builtin.service:
        name: sshd
        enabled: true
        state: started
    - name: Edit SSHD PermitRootLogin
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        insertafter: '#PermitRootLogin yes'
        line: 'PermitRootLogin prohibit-password '
      notify: Restart_sshd
#    - name: Edit SSHD PubkeyAuthentication
#      lineinfile:
#        path: /etc/ssh/sshd_config
#        regexp: '^#PubkeyAuthentication'
#        line: 'PubkeyAuthentication yes '
#      notify: restart_sshd
  handlers:
    - name: Restart_sshd
      ansible.builtin.service:
        name: sshd
        state: restarted
