---
 - name: Create and mount filesystems on wildfly servers
#   become: true
   hosts: wildfly
   gather_facts: true
   tasks:
     - name: Add group for ebiz
       ansible.builtin.group:
         name: ebiz
         gid: 20002
     - name: Add account for ebizjboss
       ansible.builtin.user:
         name: ebizjboss
         uid: 35211
         group: ebiz
         comment: "Suresh Kumar Gubbala"
         home: /home/ebizjboss
         state: present
     - name: Add group for sureshkg
       ansible.builtin.group:
         name: sureshkg
         gid: 35728
     - name: Add account for sureshkg
       ansible.builtin.user:
         name: sureshkg
         uid: 35728
         group: sureshkg
         comment: "Suresh Kumar Gubbala"
         home: /home/sureshkg
         state: present
     - name: Add group for varunp
       ansible.builtin.group:
         name: varunp
         gid: 35675
     - name: Add account for varunp
       ansible.builtin.user:
         name: varunp
         uid: 35675
         group: varunp
         comment: "Varun Patel"
         home: /home/varunp
         state: present


