---
- hosts: wildfly
  tasks:
    - name: create account for Amit (CentOS)
       - command: /usr/sbin/groupadd  -gid 35734 amitkr
       - command: /usr/sbin/groupadd  -gid 35735 akhila
       - command: /usr/sbin/useradd -m  -u 35734 -g 35734 --gecos Amit amitkr
       - command: /usr/sbin/useradd -m  -u 35735 -g 35735 --gecos Akhila akhila
      when: ansible_facts['distribution'] == "CentOS"
    - name: create account for Podolske (Ubuntu)
      shell: /usr/sbin/adduser -m -u 18480 -g 10 podolske
      when: ansible_facts['distribution'] == "Ubuntu"
