---
 - name: Create and mount filesystems on wildfly servers
#   become: true
   hosts: wildfly
   gather_facts: true
   tasks:
     - name: Copy /home/podolske/template.txt 
       template:
         dest: /home/podolske/template.txt
         src: template.j2
     - name: create /t0[1-9] /t1[01]
       ansible.builtin.file:
         path: /t01
         state: directory
