---
#    - name: install mysql and python3-mysqldb
#      apt: 
#        name: ['python3-mysqldb', 'mysql-server']
#        update_cache: yes
#        cache_valid_time: 3600
#        state: present
#      when: ansible_facts['distribution'] == "Ubuntu"
#    - name: start MySQL service
#      shell: "systemctl start mysql"
#    - name: ensure MySQL enabled
#      service: 
#        name: mysql
#        state: started
#        enabled: true
    - name: update MySQL root password
      mysql_user:
        name: root
#        host: "{{ item }}"
        host: localhost
        login_unix_socket: /var/run/mysqld/mysqld.sock
        password: "{{mysql_root_password }}"
        login_user: root
        login_password: "{{mysql_root_password }}"
        check_implicit_admin: yes
        priv: "*.*:ALL,GRANT"
#        with_items:
#        - "{{ ansible_hostname }}"
#        - 127.0.0.1
#        - localhost
    - name: create new MySQL database
      mysql_db: 
        name: testdb
        state: present 
        login_user: root
        login_password: "{{ mysql_root_password }}"
    - name: add sample data to MySQL database
      copy: src=dump.sql dest=/tmp/dump.sql
    - name: insert sample data to MySQL database
      mysql_db: name=testdb state=import target=/tmp/dump.sql login_user=root login_password="{{ mysql_root_password }}" 
    - name: create new MySQL database
      mysql_db: name=web_app state=present login_user=root login_password="{{ mysql_root_password }}" 
