---
- name: install django and make sure it is the latest version
  apt: name=python3-django state=present
  tags: django_alive
- name: check if django web_app already exists
  shell: ls -l {{ django_app_location }} | grep -c web_app
  register: djangostatus
  failed_when: djangostatus.rc == 2
- name: create  django group
  group:
    name: django
    gid: 1001
    state: present
- name: create  django user
  ansible.builtin.user:
    name: django
    uid: 1001
    shell: /bin/bash
    group: django
- name: create a directory for django app
  file: path={{ django_app_location }}/web_app mode=0755 owner=django group=django state=directory
  when: djangostatus.stdout == "0"
- name: create django app in web_app directory
  shell: django-admin startproject web_app {{ django_app_location}}/web_app
  when: djangostatus.stdout == "0"
- name: configure database to work with django app 
  copy: src=settings.py dest={{ django_app_location }}/web_app/web_app/settings.py
  when: djangostatus.stdout == "0"
- name: apply migration into mysql database 
  shell: python3 {{ django_app_location }}/web_app/manage.py migrate
  when: djangostatus.stdout == "0"
- name: populate admin with password
  shell: python3 {{ django_app_location }}/web_app/manage.py shell -c "from django.contrib.auth.models import User; User.objects.filter(username='admin').exists() or User.objects.create_superuser('admin','admin@example.com','changeme')"
  when: djangostatus.stdout == "0"
# 
