---
- name: Deploy automounter
  hosts: nis
#  become: yes

  tasks:
    - name: Installing autofs
      yum: 
        name: autofs 
        state: latest
      when: ansible_facts['distribution'] == "Rocky"


    - name: comment line with auto.misc map
      replace:
        path: /etc/auto.master
        regexp: '(^/misc*)'
        replace: '#\1'
    - name: comment line with hosts map
      replace:
        path: /etc/auto.master
        regexp: '(^/net*)'
        replace: '#\1'
    - name: comment line with dir map
      replace:
        path: /etc/auto.master
        regexp: '(^\+dir*)'
        replace: '#\1'
    - name: comment line with auto.master map
      replace:
        path: /etc/auto.master
        regexp: '(^\+auto.master)'
        replace: '#\1'
    - name: add lines to auto.master file
      lineinfile:
        dest: /etc/auto.master
        line: "{{ item }}"
      with_items:
        - '/home   nis:auto.home'
        - '/apps   nis:auto.apps'
        - '/proj   nis:auto.prod'
