---
  - name: Add group for ericw 
    ansible.builtin.group:
      name: ericw
      gid: 20204
  - name: Add account for ericw 
    ansible.builtin.user:
      name: ericw
      uid: 35400
      group: ericw
      comment: "Eric Wilkison"
      home: /home/ericw
      state: present
#      when: ansible_facts['distribution'] == "Rocky"
  - name: Copy /home/ericw/.ssh/authorized_keys
    template:
      src: authorized_keys
      dest: /home/ericw/.ssh/
      mode: 0600
  - name: Fix /home/ericw/.ssh/ ownership and permission
    file:
      path: /home/ericw/.ssh
      owner: ericw
      group: ericw
      mode: 0700
  - name: Fix /home/ericw/.ssh/authorized_keys ownership 
    file:
      path: /home/ericw/.ssh/authorized_keys
      owner: ericw
      group: ericw
  - name: create /etc/sudoers.d/ericw
    file: 
      path: /etc/sudoers.d/ericw
      state: touch
      mode: 0440
  - name: update ericw in sudoers.d
    lineinfile:
      path:  /etc/sudoers.d/ericw
      line: "ericw ALL = NOPASSWD: /usr/bin/sudosh"
  - name: Add group for pfpool
    ansible.builtin.group:
      name: pfpool
      gid: 35402
  - name: Add account for pfpool 
    ansible.builtin.user:
      name: pfpool
      uid: 35402
      group: pfpool
      home: /home/pfpool
      state: present
  - name: Copy /home/pfpool/.ssh/authorized_keys
    template:
      src: authorized_keys
      dest: /home/pfpool/.ssh/
      mode: 0600
  - name: Fix /home/pfpool/.ssh/ ownership and permission
    file:
      path: /home/pfpool/.ssh
      owner: pfpool
      group: pfpool
      mode: 0700
  - name: Fix /home/pfpool/.ssh/authorized_keys ownership 
    file:
      path: /home/pfpool/.ssh/authorized_keys
      owner: pfpool
      group: pfpool
