---
- name: Add additional lines to /etc/sysctl.d/99-sysctl.conf
  ansible.builtin.lineinfile:
    path: /etc/sysctl.d/99-sysctl.conf
    line: "{{ item }}"
  loop:
    - "net.ipv4.tcp_syncookies = 1"
    - "net.ipv4.icmp_echo_ignore_broadcasts = 1"
    - "net.ipv4.conf.all.accept_redirects = 0"
  notify: Reread_sysctl
