---
# tasks file for leapp
# - name: Prepare server to upgrade from RHEL 7 to 8
#   hosts: leapp
#   gather_facts: true
    - name: disable and stop Nagios 
      service: name=nrpe state=stopped enabled=no
    - name: ensure Nagios is uninstalled
      yum: 
        name: nrpe,nagios-plugins-*,nagios-common
        state: absent
    - name: disable and stop Salt minion 
      service: name=salt-minion state=stopped enabled=no
    - name: ensure Salt is uninstalled
      yum: 
        name: salt-minion,salt
        state: absent
    - name: remove Salt repo
      ansible.builtin.file:
        path: /etc/yum.repos.d/saltstack.repo
        state: absent
    - name: copy script to setup repoa
      ansible.builtin.copy:
        src: rocky-upgrade.sh
        dest: /tmp
