---
#- name: Deploy Web server
#  hosts: coresite
##  remote_user: ansibu1
#  become: yes
#
#  tasks:
  - name: Installing HTTPD
    yum: name=httpd state=latest

  - name: Installing MySQL package
    yum:
      name:
#      - mariadb-server
#      - mariadb-devel
#      - mariadb-connector-odbc
#      - mariadb-server-utils
      - python3-PyMySQL
      - php
      state: latest

  - name: Start and Enable MySQL Service
    service: name=mysqld state=started

  - name: Update MySQL root password
    mysql_user:
      name: root
      host: localhost
      password: s1rdhn
      login_user: root
      login_password: s1rdhn
      check_implicit_admin: yes
      priv: "*.*:ALL,GRANT"

  - name: Create a New Database called inventory
    mysql_db: name=inventory state=present login_user=root login_password=s1rdhn

  - name: Copy SQL file
    copy: src=servers.sql dest=/tmp/servers.sql

  - name: Create empty table called servers
    shell: mysql -u root -ps1rdhn inventory < /tmp/servers.sql

  - name: Copy Connection PHP File
    copy: src=connection.php dest=/var/www/html/

  - name: Copy Index PHP file
    copy: src=index.php dest=/var/www/html/

  - name: Restart Web Service
    service: name=httpd state=restarted
