
---
- name: Install basic packages 
  hosts: nova
  gather_facts: true
  become: true
  tasks:
    - name: update cache
      apt:
        update_cache: yes
    - name: copy /tmp/basic.sh
      copy:
        src: basic.sh
        dest: /tmp/basic.sh
        mode: 0755
    - name: execute basic.sh
      shell: "/tmp/basic.sh"
      register: basic
    - debug: var=basic.stdout_lines

    - name: python2 symbolic link
      ansible.builtin.file:
        src: /usr/bin/python2.7
        dest: /usr/bin/python2
        state: link

