
---
- name: disable cloud-init, enable 3 VF and setup VLANS
  hosts: nova
  gather_facts: true
  become: true
  tasks:
    - name: disable network change
      lineinfile: 
        create: true
        path: /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
        line: "network: {config: disabled}"
    - name: enable VF for ens6f0
      shell: 
        "echo 3 > /sys/class/net/ens6f0np0/device/sriov_numvfs"
    - name: enable VF for ens9f0
      shell:
        "echo 3 > /sys/class/net/ens9f0np0/device/sriov_numvfs"
    - name: turn on VLAN for ens6f0 v0
      command: "/usr/sbin/ip link set dev ens6f0np0 vf 0 vlan 110 trust on"
    - name: turn on VLAN for ens6f0 v1
      command: "/usr/sbin/ip link set dev ens6f0np0 vf 1 vlan 110 trust on"
    - name: turn on VLAN for ens6f0 v2
      command: "/usr/sbin/ip link set dev ens6f0np0 vf 2 vlan 110 trust on"
    - name: turn on VLAN for ens9f0 v0
      command: "/usr/sbin/ip link set dev ens9f0np0 vf 0 vlan 110 trust on"
    - name: turn on VLAN for ens9f0 v1
      command: "/usr/sbin/ip link set dev ens9f0np0 vf 1 vlan 110 trust on"
    - name: turn on VLAN for ens9f0 v2
      command: "/usr/sbin/ip link set dev ens9f0np0 vf 2 vlan 110 trust on"
    - name: show ip link output
      shell: ip link
      register: ip
    - debug: var=ip.stdout_lines
